### PR TITLE
Bug: Fix error message for weight command (remove w/ from message)

### LINKED ISSUE #220: Bug: Commands showing incorrect error & help messages
# Weight
image

The issue is that the `weight` command no longer uses the `w/` prefix, however it states that the weight value has to be a positive number.

image

Help message of the weight command is also not showing the updated command format 

# Find
image
Might be good to mention that prefix for `name` is optional if it is the first argument in the command

### LINKED ISSUE #284: [PE-D][Tester B] `weight` incorrect command output?
Should be `Parameters: INDEX w/WEIGHT (must be a positive float)`?
 

As a side note I think given your target audience you should use the term 'decimal' instead of float which people are less familiar with.

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: chiaryan/ped#6

### LINKED ISSUE #289: [PE-D][Tester E] error message for weight supplies wrong command format
using command `weight`, the suggested command format from error message were `Parameters: INDEX (must be a positive float) w/WEIGHT` which is incorrect according to the user guide where `WEIGHT` should not have `w/` prefix. this could mislead users to using the wrong command format. maybe, change the error message to be the same as the user guide `weight INDEX [WEIGHT]`

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: zhenghuil/ped#7

### LINKED ISSUE #294: [PE-D][Tester E] error messsage for weight gives wrong description of the command result
using the`weight` command, the error message says `Existing weight will be overwritten by the input.` which differs from the user guide description and actual usage result. from actual use, multiple use of the weight command does not overwrite the existing weight instead keeps adding weights to the contact. the user guide also says the command will add the weight to the contact, although does not say what is the result of multiple usage. basically, can change functionality to fit description or description to fit functionality. imo, overwriting seem to be more useful.

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: zhenghuil/ped#8

### LINKED ISSUE #298: [PE-D][Tester A] Wrong error message for weight command
The parameters and examples stated in the error message is wrong and following that example will throw another error.
**Error message:**

**Another error:**

**Correct format as stated in the UG:**

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: Lalelulilulela/ped#8

### PR DESCRIPTION
**Pull request by bgopi23**
Fixes #298, fixes #294, fixes #289, fixes #284, fixes #220

### CODE REVIEW

File: src/main/java/seedu/address/logic/messages/WeightCommandMessages.java [hunk 1]
```diff
@@ -11,11 +9,11 @@ public class WeightCommandMessages extends Messages {
     public static final String MESSAGE_USAGE = COMMAND_WORD
             + ": Edits the weight (in kilograms) of the person identified "
```
Comment (dillontkh) [inline src/main/java/seedu/address/logic/messages/WeightCommandMessages.java:10]: I think the weight command doesn't edit weights anymore, it can only add/remove weights now.

**Review by ruijietay — APPROVED** [review]
LGTM

**Review by dillontkh — APPROVED** [review]
LGTM!

**Review by jjchee77 — APPROVED** [review]
LGTM!

**Review by ruijietay — APPROVED** [review]
LGTM

File: src/main/java/seedu/address/logic/messages/WeightCommandMessages.java [hunk 2]
```diff
@@ -1,21 +1,17 @@
...
 public class WeightCommandMessages extends Messages {
 
     public static final String COMMAND_WORD = "weight";
     public static final String MESSAGE_USAGE = COMMAND_WORD
-            + ": Edits the weight (in kilograms) of the person identified "
-            + "by the index number used in the last person listing.\n"
-            + "Existing weight will be overwritten by the input.\n"
-            + "Parameters: INDEX (must be a positive float) "
-            + CliSyntax.PREFIX_WEIGHT + "WEIGHT\n"
+            + ": Adds a weight (in kg) to a client specified by the index number used in the last person listing.\n"
```
Comment (bgopi23) [inline src/main/java/seedu/address/logic/messages/WeightCommandMessages.java:10]:
```suggestion
            + ": Adds a weight (in kg) to the client specified by the index number used in the person list.\n"
```

File: src/main/java/seedu/address/logic/messages/WeightCommandMessages.java [hunk 3]
```diff
@@ -1,21 +1,17 @@
 package seedu.address.logic.messages;
 
-import seedu.address.logic.parser.CliSyntax;
-
 /**
  * Messages used by ListCommand and associated classes.
```
Comment (bgopi23) [inline src/main/java/seedu/address/logic/messages/WeightCommandMessages.java:4]:
```suggestion
 * Messages used by WeightCommand and associated classes.
```

File: src/main/java/seedu/address/logic/messages/WeightCommandMessages.java [hunk 4]
```diff
@@ -1,21 +1,17 @@
...
 public class WeightCommandMessages extends Messages {
 
     public static final String COMMAND_WORD = "weight";
     public static final String MESSAGE_USAGE = COMMAND_WORD
-            + ": Edits the weight (in kilograms) of the person identified "
-            + "by the index number used in the last person listing.\n"
-            + "Existing weight will be overwritten by the input.\n"
-            + "Parameters: INDEX (must be a positive float) "
-            + CliSyntax.PREFIX_WEIGHT + "WEIGHT\n"
+            + ": Adds a weight (in kg) to the client specified by the index number used in the person list.\n"
```
Comment (bgopi23) [inline src/main/java/seedu/address/logic/messages/WeightCommandMessages.java:10]:
```suggestion
            + ": Adds a weight (in kg) to the client specified by the index number used in the client list.\n"
```
