### PR TITLE
Bugfix: Update phone validation

### LINKED ISSUE #101: Bug: Incorrect phone number validation
Currently, the phone attribute is validated against a regex that requires the value to contain only digits and have a minimum length of 3.
This differs from reality and hence should be rectified.

Goals:
1. Validate phone number against a correct regex expression
2. Optionally add support for classification of phone numbers based on country

### PR DESCRIPTION
**Pull request by jjchee77**
Resolves #101 

Phone number is now validated against the following regex expression: `^[689]\d{7}$`
Added and modified related test cases accordingly.

### CODE REVIEW

**Review by dillontkh — APPROVED** [review]
LGTM!

File: src/main/java/seedu/address/model/person/Phone.java [hunk 1]
```diff
@@ -11,8 +11,8 @@ public class Phone {
 
 
     public static final String MESSAGE_CONSTRAINTS =
-            "Phone numbers should only contain numbers, and it should be at least 3 digits long";
-    public static final String VALIDATION_REGEX = "\\d{3,}";
+        "Phone numbers should only contain numbers, starts with either '8' or '9' and be a total of 8 digits long";
+    public static final String VALIDATION_REGEX = "^[89]\\d{7}$";
```
Comment (ruijietay) [inline src/main/java/seedu/address/model/person/Phone.java:15]:
```suggestion
    public static final String VALIDATION_REGEX = "^[689]\\d{7}$";
```

**Review by ruijietay — APPROVED** [review]
One nit to pick regarding phone number regex, but apart from that, LGTM!
